name: Sync Upstream

# This runs every day on 1801 UTC
on:
  schedule:
    - cron: '46 13 * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Opf Upstream Repository
        uses: rovast/sync-upstream-repo@v0.0.1
        with: 
          upstream_repo: https://github.com/opf/openproject # opf
          upstream_branch: dev
          downstream_branch: compare
